### PR TITLE
#28 - Added very simple responsive option

### PR DESCRIPTION
**Pull request by RedMike**
I've written a very simple change to make it work better on responsive pages, as in issue #28. Worked fine for my use-case, and I'm fairly sure custom CSS on the container allows for some flexibility.

Changed the SVG so that the width/height gets turned into a viewBox property with the original size, and then width is set to fill container. This makes it so the container now defines the width of the graph. In the 'responsive' CSS file, had to remove the height property to make the text below the graph not clip into it. There might be a better solution there.

### CODE REVIEW

**Comment by IonicaBizau** [comment]
Sorry for delay, last week was tricky (storms, no power/internet etc). I will review this soon! Thanks! 🍀

**Review by IonicaBizau — APPROVED** [review]
Looks good! ✨ I will test it locally before merging.

**Comment by Eshpelin** [comment]
Sorry for bugging, but this seems to be a nice way to circumvent the issue. Would appreciate the merge taking place.

**Comment by IonicaBizau** [comment]
Whoups, do ping me if I don't merge it tomorrow! I was traveling and totally forgot about this... Sorry!

**Comment by Eshpelin** [comment]
Pinging since I just randomly remembered this.

**Comment by IonicaBizau** [comment]
I'm in the mountains, with my iPhone on the top of a 12 meter long piece of wood, outside is daaaark and cold and I'm merging this PR! 🎉 😁 🌟 

Thanks a lot!

**Comment by Eshpelin** [comment]
haha nice :) Thanks :) Enjoy your vacation.

**Pull request merged**
