### PR TITLE
github-calendar 2.3.0

### PR DESCRIPTION
**Pull request by IonicaBizau**
Remove skylines add -- thanks @hughesjs! :cake: /cc #148

### CODE REVIEW

**Comment by hughesjs** [comment]
@IonicaBizau I might be missing something, but do you need to merge #148 too? This PR only seems to update the minified version.

**Comment by IonicaBizau** [comment]
@hughesjs Indeed! Thanks!

**Comment by hughesjs** [comment]
No worries @IonicaBizau - Will the updated version be auto-deployed to NPM?

**Comment by IonicaBizau** [comment]
@hughesjs Yes, it should be published already — I am wondering if the live demo is somehow cached.

**Comment by hughesjs** [comment]
@IonicaBizau Could well be... Did you check my fix? Could well be I screwed it up... It's been ages since I've worked with vanilla JS so I sort of trial and errored it in the console so I may well have messed it up transferring it from there into the source

**Comment by hughesjs** [comment]
Actually, scratch that, just checked the preview and looks good to me!

**Comment by IonicaBizau** [comment]
Yup, it's live now. Thank you so much! 😁

**Pull request merged**
