### PR TITLE
Fixed Syntax Error

### PR DESCRIPTION
**Pull request by GiselaK**
Added missing '>' for opening script tag line 29

### CODE REVIEW

**Comment by IonicaBizau** [comment]
Oh, thank you for this, @GiselaKay! 😄 ✨

**Comment by IonicaBizau** [comment]
Would be good to fix it in the [`package.json`](https://github.com/IonicaBizau/github-calendar/blob/edb65cfeebb0ef215b2d9eda430681f13dc412cf/package.json#L46) too. The README.md file is generated.

**Comment by GiselaK** [comment]
Ahh, will do!

**Comment by IonicaBizau** [comment]
@GiselaKay This is [*How I npm*](https://ionicabizau.net/blog/33-how-i-npm), but it's an undocumented part... 😭 Didn't have time to document it somewhere.

**Pull request merged**
